### ISSUE TITLE
ResponsiveSizer widget doesn't exist

### ISSUE THREAD

**Issue by Macacoazul01** [TechnoUrmish/Sizer#35] opened 2021-11-11 21:40 UTC
The readme of the package tells us to wrap materialapp with ResponsiveSizer:

![image](https://user-images.githubusercontent.com/57464965/141372507-a1730a55-f4fa-4c2f-80e0-5701002b2189.png)

But it doesn't exist in the library:

![image](https://user-images.githubusercontent.com/57464965/141372775-3d9e5352-5e14-4443-9eb8-6fadbd57837d.png)

**Comment by evanholt1** [comment] 2021-11-15 07:15
Use `Sizer` instead.

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Sizer(
      builder: (context, orientation, deviceType) => MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: WelcomeScreen(),
      ),
    );
  }
}
```

**Comment by Macacoazul01** [comment] 2021-11-15 13:02
I already use sizer (look at the print), the problem is that when the page size changes, the height (.h) and width (.w) settings of the package don't.

**Comment by calvintam236** [comment] 2021-11-21 22:32
Duplicate of #23

**Closed** 2021-11-25 21:14 UTC
